Vagrant.configure("2") do |config|
    config.vm.box = 'ubuntu/wily64'
    config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true

    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

    config.vm.provision "shell", path: "./bootstrap.sh"
    #config.trigger.after :up, :execute => "vagrant reload"
    #config.trigger.after :provision do
    #    run "vagrant reload"
    #end

    config.vm.synced_folder "../src/", "/src"
    config.vm.provider "virtualbox" do |v|
        v.memory = 3072
        v.cpus = 2
    end
end
